
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opczyuxraleahrnzrxbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wY3p5dXhyYWxlYWhybnpyeGJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwNTQzNTQsImV4cCI6MjA1NjYzMDM1NH0.5HeR4rqrIyAMy6FmviQn2VnazOUqjIh8r5EHgISuNKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  },
  global: {
    fetch: fetch
  },
  db: {
    schema: 'public'
  },
  storage: {
    // Storage options
  }
});
